# golangci-lint 配置文件
# 更多信息: https://golangci-lint.run/usage/configuration/

version: "2"

run:
  # 超时时间
  timeout: 5m

  # 要检查的模块（空表示所有）
  modules-download-mode: readonly

  # Go 版本（用于兼容性检查，设置为 golangci-lint 构建时使用的版本）
  go: "1.24"

# Linter 配置
linters:
  # 启用的 linter
  enable:
    - errcheck          # 检查错误是否被处理
    - govet             # go vet 检查
    - ineffassign       # 检查未使用的赋值
    - staticcheck       # 静态分析
    - unused            # 检查未使用的代码
    - misspell          # 拼写检查
    - revive            # Go 代码检查工具
    - gocritic          # Go 代码审查工具
    - copyloopvar       # 检查循环中的引用
    - gosec             # 安全检查
    - unconvert         # 检查不必要的类型转换
    - unparam           # 检查未使用的参数

  # linter 配置（v2 格式：settings 嵌套在 linters 下）
  settings:
    errcheck:
      # 报告所有错误，包括未导出的函数
      check-type-assertions: true
      check-blank: true

    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - dupImport # 允许重复导入（某些情况下需要）

    govet:
      # 启用所有检查
      enable-all: true

    revive:
      # 规则配置
      rules:
        - name: exported
          severity: warning
        - name: var-naming
          severity: error
          arguments:
            - ["allowAllCaps"] # 允许 ALL_CAPS 命名风格（用于常量）
            - ["allowPrivate"] # 允许私有变量使用 camelCase
        - name: package-comments
          severity: warning
        # 常量命名规范（根据 CODE_STYLE.md 和 CONTRIBUTING.md）：
        # - 所有导出的常量必须使用 ALL_CAPS (UPPER_SNAKE_CASE)
        # - 错误变量（以 Err 开头）可以使用 PascalCase（这是 Go 的约定）
        # - 其他导出的变量使用 PascalCase
        # 注意：var-naming 规则会检查所有导出的变量和常量
        # 但由于 revive 无法精确区分常量和变量，需要手动确保常量使用 ALL_CAPS
#
#   gosec:
#     # 排除一些误报
#     excludes:
#       - G104 # 错误未检查（某些情况下可以接受）
#       - G107 # HTTP 请求（某些情况下需要）

# 问题配置
issues:
  # 排除的问题规则
  exclude-rules:
    # 排除测试文件中的某些检查
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    # 允许常量使用 ALL_CAPS 命名（根据 CODE_STYLE.md 和 CONTRIBUTING.md）
    # 排除所有对常量使用 ALL_CAPS 的 var-naming 检查
    - text: "don't use ALL_CAPS in Go names; use CamelCase"
      linters:
        - revive

  # 最大问题数（0 表示无限制）
  max-issues-per-linter: 0
  max-same-issues: 0

  # 排除问题模式
  exclude:
    # 排除一些常见的误报
    - "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*printf?|os\\.(Un)?Setenv). is not checked"
    - "exported: exported (type|function|method|field|const) .* should have comment"
    # 允许常量使用 ALL_CAPS 命名（根据 CODE_STYLE.md 和 CONTRIBUTING.md）
    - "var-naming: don't use ALL_CAPS in Go names; use CamelCase"

# 输出配置（v2.5.0 中某些输出选项可能不被支持）
# output:
#   formats:
#     - format: colored-line-number

